#!/usr/bin/env python3
"""
Helper script to get ENTSO-E API token
This should be run manually when needed, not part of main code
"""
import os
import getpass
from pathlib import Path
import sys

print("=" * 60)
print("ENTSO-E API Token Helper")
print("=" * 60)
print("\nThis script helps you get your API token from ENTSO-E")
print("Your credentials are only used locally and not stored\n")

# Check if .env exists
env_file = Path('.env')

if env_file.exists():
    print("⚠️  .env file already exists")
    response = input("Do you want to update it? (y/n): ")
    if response.lower() != 'y':
        print("Exiting...")
        sys.exit(0)

print("\n📝 Instructions:")
print("1. Go to https://transparency.entsoe.eu/")
print("2. Login with your credentials")
print("3. Go to 'My Account Settings'")
print("4. Generate or copy your security token")
print("5. Paste it below\n")

# Get token interactively
api_token = getpass.getpass("Enter your ENTSO-E API token: ")

if not api_token:
    print("❌ No token provided")
    sys.exit(1)

# Write to .env
with open('.env', 'w') as f:
    f.write(f"# ENTSO-E API Configuration\n")
    f.write(f"# Generated by script - DO NOT COMMIT TO GIT!\n")
    f.write(f"ENTSOE_API_KEY={api_token}\n")

print("✅ Token saved to .env file")
print("⚠️  Remember: Never commit .env to git!")
print("\nYou can now run the main analysis with: python main.py")