name: battery_opt
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0  # Includes HiGHS solver from v1.9+

  # PV modeling
  - pvlib-python>=0.10.0

  # API and web
  - requests>=2.28.0
  - python-dotenv>=1.0.0

  # OR solvers (all free, choose one or more):
  - ortools-python>=9.0  # Google OR-Tools with CBC, GLOP, CP-SAT
  - pulp>=2.7.0          # Includes CBC solver
  - highspy>=1.5         # State-of-the-art LP/MIP solver
  # - glpk                # GNU solver (backup option)

  # Visualization
  - matplotlib>=3.7.0
  - plotly>=5.14.0

  # Utilities
  - pytz>=2023.3
  - openpyxl>=3.1.0

  # pip only packages (not in conda-forge)
  - pip
  - pip:
    - entsoe-py>=0.6.0  # ENTSO-E API wrapper